experiment_name: "VAS_BERTWhisperOTKE"
mode: "kfold"
model_name: "BERTWhisperOTKE"
# seeds: [42, 2023, 2024, 88, 1234, 2025, 2026, 2027, 2028, 2029]
seeds: [42]
data_type: "multimodal"
model_output_dir: "models"
early_stopping_patience: 3
verbose: true
log_dir: "results"
use_wandb: true
text_encoder: "bert-base-uncased"
audio_encoder: "openai/whisper-small"

model:
  audio_encoder: "openai/whisper-small"
  text_encoder: "bert-base-uncased"
  num_labels: 3
  dropout: 0.1

data:
  data_path: "./data/VAS"
  batch_size: 10
  num_proc: 1
  audio_chunk_duration: 30 
  max_text_length: 512
  num_folds: 10

training:
  eval_strategy: "epoch"
  save_strategy: "epoch"
  learning_rate: 0.00002
  save_steps: 1
  eval_steps: 1
  save_total_limit: 1
  max_grad_norm: 1.0
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  num_train_epochs: 10
  logging_steps: 1
  load_best_model_at_end: true
  metric_for_best_model: "eval_loss"
  greater_is_better: false
  report_to: "wandb"
  max_steps: -1